export const ABSENCE_TYPE_CODES = {
    PAID_LEAVE: 'CP',
    RTT: 'RTT',
    SICK: 'MAL',
    MATERNITY: 'MAT',
    PATERNITY: 'PAT',
    CHILD_SICK: 'ENF',
    BEREAVEMENT: 'DEUIL',
    MOVING: 'DEMEN',
    UNPAID: 'SSOL',
    RECOVERY: 'RECUP',
    TRAINING: 'FORM',
    ACCIDENT: 'AT',
};
export const DEFAULT_ABSENCE_TYPES = [
    {
        code: 'CP',
        label: 'Congés payés',
        category: 'paid_leave',
        color: '#4F46E5',
        requiresApproval: true,
        isPaid: true,
        maxDaysPerYear: '25',
    },
    {
        code: 'RTT',
        label: 'RTT',
        category: 'rtt',
        color: '#7C3AED',
        requiresApproval: true,
        isPaid: true,
    },
    {
        code: 'MAL',
        label: 'Arrêt maladie',
        category: 'sick',
        color: '#DC2626',
        requiresJustification: true,
        requiresApproval: false,
        impactsPayroll: true,
    },
    {
        code: 'MAT',
        label: 'Congé maternité',
        category: 'maternity',
        color: '#EC4899',
        requiresJustification: true,
        requiresApproval: false,
        maxDaysPerYear: '112',
    },
    {
        code: 'PAT',
        label: 'Congé paternité',
        category: 'paternity',
        color: '#0EA5E9',
        requiresJustification: true,
        requiresApproval: false,
        maxDaysPerYear: '25',
    },
    {
        code: 'ENF',
        label: 'Enfant malade',
        category: 'family',
        color: '#F59E0B',
        requiresJustification: true,
        requiresApproval: false,
        maxDaysPerYear: '12',
    },
    {
        code: 'DEUIL',
        label: 'Congé deuil',
        category: 'family',
        color: '#6B7280',
        requiresJustification: true,
        requiresApproval: false,
    },
    {
        code: 'SSOL',
        label: 'Congé sans solde',
        category: 'unpaid',
        color: '#9CA3AF',
        requiresApproval: true,
        isPaid: false,
    },
    {
        code: 'RECUP',
        label: 'Récupération',
        category: 'other',
        color: '#10B981',
        requiresApproval: true,
        isPaid: true,
    },
    {
        code: 'AT',
        label: 'Accident du travail',
        category: 'sick',
        color: '#EF4444',
        requiresJustification: true,
        requiresApproval: false,
        impactsPayroll: true,
    },
];
//# sourceMappingURL=absence-types.js.map