export const ABSENCE_TYPE_CODES = {
  PAID_LEAVE: 'CP',
  RTT: 'RTT',
  SICK: 'MAL',
  MATERNITY: 'MAT',
  PATERNITY: 'PAT',
  CHILD_SICK: 'ENF',
  BEREAVEMENT: 'DEUIL',
  MOVING: 'DEMEN',
  UNPAID: 'SSOL',
  RECOVERY: 'RECUP',
  TRAINING: 'FORM',
  ACCIDENT: 'AT',
} as const

export const DEFAULT_ABSENCE_TYPES = [
  {
    code: 'CP',
    label: 'Congés payés',
    category: 'paid_leave' as const,
    color: '#4F46E5',
    requiresApproval: true,
    isPaid: true,
    maxDaysPerYear: '25',
  },
  {
    code: 'RTT',
    label: 'RTT',
    category: 'rtt' as const,
    color: '#7C3AED',
    requiresApproval: true,
    isPaid: true,
  },
  {
    code: 'MAL',
    label: 'Arrêt maladie',
    category: 'sick' as const,
    color: '#DC2626',
    requiresJustification: true,
    requiresApproval: false,
    impactsPayroll: true,
  },
  {
    code: 'MAT',
    label: 'Congé maternité',
    category: 'maternity' as const,
    color: '#EC4899',
    requiresJustification: true,
    requiresApproval: false,
    maxDaysPerYear: '112',
  },
  {
    code: 'PAT',
    label: 'Congé paternité',
    category: 'paternity' as const,
    color: '#0EA5E9',
    requiresJustification: true,
    requiresApproval: false,
    maxDaysPerYear: '25',
  },
  {
    code: 'ENF',
    label: 'Enfant malade',
    category: 'family' as const,
    color: '#F59E0B',
    requiresJustification: true,
    requiresApproval: false,
    maxDaysPerYear: '12',
  },
  {
    code: 'DEUIL',
    label: 'Congé deuil',
    category: 'family' as const,
    color: '#6B7280',
    requiresJustification: true,
    requiresApproval: false,
  },
  {
    code: 'SSOL',
    label: 'Congé sans solde',
    category: 'unpaid' as const,
    color: '#9CA3AF',
    requiresApproval: true,
    isPaid: false,
  },
  {
    code: 'RECUP',
    label: 'Récupération',
    category: 'other' as const,
    color: '#10B981',
    requiresApproval: true,
    isPaid: true,
  },
  {
    code: 'AT',
    label: 'Accident du travail',
    category: 'sick' as const,
    color: '#EF4444',
    requiresJustification: true,
    requiresApproval: false,
    impactsPayroll: true,
  },
]
