server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    server_tokens off;

    # Proxy vers l'API (evite les problemes CORS et VITE_API_URL non defini)
    location /api/ {
        proxy_pass http://api-svc.nexusrh.svc.cluster.local:4001/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets statiques avec cache long
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # En-têtes de sécurité
    add_header X-Content-Type-Options  "nosniff"                        always;
    add_header X-Frame-Options         "SAMEORIGIN"                     always;
    add_header X-XSS-Protection        "1; mode=block"                  always;
    add_header Referrer-Policy         "strict-origin-when-cross-origin" always;

    # Pas de log pour health checks
    location = /favicon.ico { access_log off; log_not_found off; }
}
