{{- if .Values.ingress.enabled -}}
{{- $ns := include "nexusrh.namespace" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexusrh-ingress
  namespace: {{ $ns }}
  labels:
    {{- include "nexusrh.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer | quote }}
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.global.domain }}
        - {{ .Values.global.apiDomain }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc
                port:
                  number: {{ .Values.web.port }}
    - host: {{ .Values.global.apiDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: {{ .Values.api.port }}
{{- end }}
