apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "nexusrh.namespace" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.pss.enforceLevel | default "restricted" }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: {{ .Values.pss.warnLevel | default "restricted" }}
    pod-security.kubernetes.io/warn-version: latest
    {{- include "nexusrh.labels" . | nindent 4 }}
{{- if .Values.limitRange.enabled }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "nexusrh.fullname" . }}-limits
  namespace: {{ include "nexusrh.namespace" . }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.container.defaultCpu }}
        memory: {{ .Values.limitRange.container.defaultMemory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.container.defaultRequestCpu }}
        memory: {{ .Values.limitRange.container.defaultRequestMemory }}
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
{{- end }}
{{- if .Values.resourceQuota.enabled }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "nexusrh.fullname" . }}-quota
  namespace: {{ include "nexusrh.namespace" . }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requests.cpu }}
    requests.memory: {{ .Values.resourceQuota.requests.memory }}
    limits.cpu: {{ .Values.resourceQuota.limits.cpu }}
    limits.memory: {{ .Values.resourceQuota.limits.memory }}
    pods: {{ .Values.resourceQuota.pods | quote }}
{{- end }}
