apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: nexusrh-ci

patches:
  - path: patches.yaml
    target:
      kind: Ingress
      name: nexusrh-ingress

  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: nexusrh-api

  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: nexusrh-web

  # Surcharge du ConfigMap pour la prod (patch JSON merge)
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nexusrh-config
      data:
        NODE_ENV: production
        LOG_LEVEL: warn
    target:
      kind: ConfigMap
      name: nexusrh-config

images:
  - name: nexusrh/api
    newName: ghcr.io/couldevlop/nexusrh-ci-api
    newTag: latest
  - name: nexusrh/web
    newName: ghcr.io/couldevlop/nexusrh-ci-web
    newTag: latest
  - name: nexusrh/worker
    newName: ghcr.io/couldevlop/nexusrh-ci-worker
    newTag: latest
